version: '3'
services:
  ros:
    build: .
    image: parloma/ci
    volumes:
      - ./store:/store
    environment:
      - POLL_TIME=2
      - CONFIG_SERVER=docker
    ports:
      - 9090:9090
      - 5000:5000
    privileged: true
    command: "supervisord -n"
